name: Demo Build
run-name: ${{ github.actor }} bruh
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get update
      - run: apt-get install -y
      - run: apt-get install -y build-essential
      - run: echo "ALL DEPS INSTALLED"
      - run: make -B
